apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
    type: frontend

spec:
  template:
    metadata:
      name: petclinic-pod
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic-container
          image: laxmisavalagi/petclinic_2020:latest
  replicas: 3
  selector:
    matchLabels:
      app: petclinic

