apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
     app: petclinic
